project:
  type: website
  output-dir: _site

website:
  title: "ベイジアンいろは"
  sidebar:
    style: "floating"
    contents:
      - section: "Web Performance ROI Analysis"
        contents:
          - notebooks/01_web_performance/README.md
          - notebooks/01_web_performance/roi_decision.ipynb
      - section: "spatial model Analysis"
      - contents:
          - notebooks/02_hockey_gotender/README.md
          - notebooks/02_hockey_gotender/hockey_spatial_analysis.ipynb
          - notebooks/02_hockey_gotender/privacy_utils.py

format:
  html:
    theme: lux
    toc: true

# 重要：Poetryの仮想環境を反映させるためのJupyter設定
jupyter: python3

execute:
  freeze: auto  # 変更があった時だけ再実行。または true (実行しない)
